name: Build & Release

on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get tag
      run: echo ::set-output name=VERSION_TAG::${GITHUB_REF/refs\/tags\//}
      id: get_tag
      
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}   
        
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
        cache: 'yarn'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies & Build
      run: yarn --frozen-lockfile && yarn build
    
    - name: Bundle
      run: |
        mkdir -p ./temp/npwd_midofey_garage
        cp ./{README.md,fxmanifest.lua} ./temp/npwd_midofey_garage
        cp -r ./client ./temp/npwd_midofey_garage
        cp -r ./server ./temp/npwd_midofey_garage
        cp -r ./web ./temp/npwd_midofey_garage
        cd ./temp && zip -r ../npwd_midofey_garage.zip ./npwd_midofey_garage
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      id: auto_release
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: NPWD Midofey Garage App | ${{ steps.get_tag.outputs.VERSION_TAG }}
        prerelease: false
        files: npwd_midofey_garage.zip

      env:
        CI: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
